title: DevHub
baseurl: ""
url: "https://Dylan01157.github.io" # ton site GitHub Pages
collections:
theme: minima


collections:
  questions:
    output: true
    permalink: /questions/:name/

markdown: kramdown

theme: minima
